# Site
repository: sproogen/modern-resume-theme
favicon: images/logo.png


# Personal info
name: Param Popat
title: MS in Computer Science @ Columbia University
email: pvp2109@columbia.edu
phone: 440-454-4561
website: parampopat.me/


darkmode: false


# Social links
twitter_username: Parampopat
github_username:  parampopat
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: parampopat
linkedin_username: parampopat
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# Additional icon links
additional_links:
- title: Medium
  icon: fa-medium
  url: https://medium.com/@parampopat

- title: Resume
  icon: fa-file
  url: https://parampopat.me/resume/resume.html

  
# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Param and I'm a Computer Science Graduate working towards developing Fair and Robust Machine learning Systems.

  I am most skilled in: <mark>Python</mark>, <mark>SQL</mark>, <mark>Tensorflow</mark>, <mark>AWS</mark> and <mark>Tableau</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Machine Learning and Software Engineering some of my other interests and hobbies are:
  - Photography
  - Cooking


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
